export const GET_MOVIE_DATA = 'GET_MOVIE_DATA';
export const GET_MOVIE_DATA_BY_PAGE = 'GET_MOVIE_DATA_BY_PAGE';
export const GET_MOVIE_DATA_BY_SEARCH = 'GET_MOVIE_DATA_BY_SEARCH';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
